// Locker LOADING
export const LOCKER_NONE = "LOCKER_NONE";
export const LOCKER_LOADING_REQUEST = "LOCKER_LOADING_REQUEST";
export const LOCKER_LOADING_SUCCESS = "LOCKER_LOADING_SUCCESS";
export const LOCKER_LOADING_FAILURE = "LOCKER_LOADING_FAILURE";