// Locker LOADING
export const LOCKER_NONE = "LOCKER_NONE";
export const LOCKER_LOADING_REQUEST = "LOCKER_LOADING_REQUEST";
export const LOCKER_LOADING_SUCCESS = "LOCKER_LOADING_SUCCESS";
export const LOCKER_LOADING_FAILURE = "LOCKER_LOADING_FAILURE";

// Locker CREATE
export const LOCKER_CREATE_REQUEST = "LOCKER_CREATE_REQUEST";
export const LOCKER_CREATE_SUCCESS = "LOCKER_CREATE_SUCCESS";
export const LOCKER_CREATE_FAILURE = "LOCKER_CREATE_FAILURE";

// Locker DELETE
export const LOCKER_DELETE_REQUEST = "LOCKER_DELETE_REQUEST";
export const LOCKER_DELETE_SUCCESS = "LOCKER_DELETE_SUCCESS";
export const LOCKER_DELETE_FAILURE = "LOCKER_DELETE_FAILURE";

// Locker EDIT
export const LOCKER_EDIT_REQUEST = "LOCKER_EDIT_REQUEST";
export const LOCKER_EDIT_SUCCESS = "LOCKER_EDIT_SUCCESS";
export const LOCKER_EDIT_FAILURE = "LOCKER_EDIT_FAILURE";

// LOGIN
export const LOGIN_REQUEST = "LOGIN_REQUEST";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAILURE = "LOGIN_FAILURE";

// LOGOUT
export const LOGOUT_REQUEST = "LOGOUT_REQUEST";
export const LOGOUT_SUCCESS = "LOGOUT_SUCCESS";
export const LOGOUT_FAILURE = "LOGOUT_FAILURE";

// User LOADING
export const USER_LOADING_REQUEST = "USER_LOADING_REQUEST";
export const USER_LOADING_SUCCESS = "USER_LOADING_SUCCESS";
export const USER_LOADING_FAILURE = "USER_LOADING_FAILURE";

// CLEAR ERROR
export const CLEAR_ERROR_REQUEST = "CLEAR_ERROR_REQUEST";
export const CLEAR_ERROR_SUCCESS = "CLEAR_ERROR_SUCCESS";
export const CLEAR_ERROR_FAILURE = "CLEAR_ERROR_FAILURE";

// REGISTER
export const REGISTER_REQUEST = "REGISTER_REQUEST";
export const REGISTER_SUCCESS = "REGISTER_SUCCESS";
export const REGISTER_FAILURE = "REGISTER_FAILURE";